---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment1
  labels:
    type: newproxy
    author: intelliqit
spec:
  replicas: 2
  selector:
    matchLabels:
      type: newproxy
  template:
    metadata:
      name: nginx-pod
      labels:
        type: newproxy
    spec:
      containers:
        - name: mynginx
          image: nginx:1.23
          ports:
            - containerPort: 80
              hostPort: 9090
...
