---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  lables:
    author: intelliqit
    type: ci-cd
spec:
  containers:
    - name: myjenkins
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          hostPort: 9090
...            
